const deck = [
  { id: 1,
    img:"./images/Card_circle.png",
  },
  { id: 2,
    img:"./images/Card_star.png",
  },
  { id: 3,
    img: "./images/Card_polygon.png",
  },
  { id: 4,
    img: "./images/Card_square.png",
  },
  { id: 5,
    img: "./images/Card_x.png",
  },
  { id: 6,
    img: "./images/Card_triangle.png",
  },
  { id: 7,
    img: "./images/Card_triangle.png",
  },
  { id: 8,
    img: "./images/Card_x.png",
  },
  { id: 9,
    img: "./images/Card_square.png",
  },
  { id: 10,
    img: "./images/Card_polygon.png",
  },
  { id: 11,
    img: "./images/Card_star.png",
  },
  { id: 12,
    img: "./images/Card_circle.png",
  },
];

export default deck;